### ISSUE TITLE
"Pull changes from remote" for the current branch

### ISSUE THREAD

**Issue by dwiyatci** [m-hall/vscode-git-branch-sidebar#10]
Upon right-clicking, "Pull changes from remote" menu item pops-up for other branches than current. I think it'd be nice if the current branch has this menu item, too (i.e. so that I could easily pull to "refresh" the branch when somebody else has made changes/pushed to the remote branch counterpart 😬).

**Other branch**:
<img width="490" alt="Screenshot 2024-01-06 at 18 55 47" src="https://github.com/m-hall/vscode-git-branch-sidebar/assets/4405796/e8251f61-ad1b-41b3-a886-221818b6568f">

**Current branch**:
<img width="490" alt="Screenshot 2024-01-06 at 18 56 15" src="https://github.com/m-hall/vscode-git-branch-sidebar/assets/4405796/f999ad6a-f05f-4dfd-aa4c-dfb2b709fd85">

Thanks.

**Comment by m-hall** [comment]
That's probably worth adding. I didn't think of it because I keep it in the source control view, where there's a button to sync the current branch already.
~~It would have to work a little different than the existing one, because it would only be available when the branch is otherwise clean, but there's no reason not to include it I think.~~
Slight mind change on this one: the built-in git extension doesn't distinguish the "clean" state for menu commands, so I'm gonna add the command and ignore clean state as well. It'll just fail sometimes due to divergent changes.

**Comment by m-hall** [comment]
With 1.6.2 this should now work :)
