### ISSUE TITLE
Custom icon when moved to the Activity Bar

### ISSUE THREAD

**Issue by dwiyatci** [m-hall/vscode-git-branch-sidebar#9]
I move the extension out to the Activity Bar for even quicker access, but unfortunately the extension's icon remains the same as the built-in Source Control's icon. Can this be improved so that it's easier on the eyes? Thank you.

<img width="490" alt="Screenshot 2024-01-06 at 18 50 24" src="https://github.com/m-hall/vscode-git-branch-sidebar/assets/4405796/5b3ae4db-9f46-4174-94c4-272ae2fb169a">

**Comment by m-hall** [comment]
Part of the goal with this extension was to specifically exist within the `Source Control` view, rather than adding a new view to the sidebar. That was why I did not add a new icon for it.
It's intended to just add a small feature that I felt was missing from the built-in Git view, and not be a fully fleshed out Git extension. Those already exist (eg. GitLens)

I believe that I could add an icon which becomes available should you move it out of the source control view, so I think that's worth investigating, as it wouldn't go against the spirit of this extension, and would add value to people with needs a bit different than my own (such as you 🙂)

**Comment by m-hall** [comment]
With 1.6.2 this should now have a custom icon.
